### ISSUE TITLE
自身遇到的广州黑名单公司

### ISSUE THREAD

**Issue by z992** [lxl0928/it_blacklist_company#16]
公司名称：广州天脉信息科技有限公司
恶行：拖欠员工工资拒不发还，项目做完就赶人走，当时公司内一共也就十多个人，小外包公司，项目做完了，赶了3,4个人走。
当时所接触的公司负责人：严炳欢

**Comment by lxl0928** [comment]
https://github.com/lxl0928/it_blacklist_company/blob/master/guangzhou/README.md
