### ISSUE TITLE
南京大黄鸭信息技术有限公司

### ISSUE THREAD

**Issue by blackdata-cyber** [lxl0928/it_blacklist_company#18]
公司一共只有不到十个人，几个外包项目都是驻场办公，有的在金证，有的在莱斯，公司没有自己的办公地址，也不提供办公设备，电脑要自己带。老板（兼项目经理）连业务需求够搞不清楚，瞎指挥，可以连续说话三个小时不喝水（声音超大，根本无法安静工作）。晚上加班到九点甚至更晚且没有加班费，甚至连晚饭都没有，打车报销就更不用想了（老板名言：不管加不加班，你都是要回家的，所以通勤产生的费用，不应该公司承担，如果公司承担，这笔钱算报销还是算补贴呢），周末无偿加班没有任何补贴。每月28号发上一个月的工资，偶尔还会出现延迟的情况（某员工曾因公司延迟发放工资导致信用卡还款逾期，跟老板沟通，老板表示：“信用卡逾期你自己想办法解决呀，你跟我说我们也没办法呀我自己的信用卡还逾期了呢！”）。每月都有各种理由扣工资，少则七八百，多则一两千；离职必扣工资，曾经某离职员工工资被扣成了负数，是的，你没看错，负数。项目进入最后阶段，老板（项目经理）仍然对需求一无所知，依旧大声说话瞎指挥，戾气冲天，项目组成员没有一个看好项目。

**Comment by lxl0928** [comment]
https://github.com/lxl0928/it_blacklist_company/blob/master/nanjing/README.md  已更新
